stages:
  - Static-analysis
  - Build

"Windows Build":
  stage: Build
  only:
    - ci_workflows
  script:
    - mkdir build && cd build
    - Enter-VsDevShell -VsInstallPath "$vsPath" -DevCmdArguments "-arch=x64 -host_arch=x64" -SkipAutomaticLocation
    - cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja -DQt6_DIR="$qtInstallPath/lib/cmake/Qt6"
    - cmake --build . --config Release
