#ifndef EXTENSIONSYSTEM_GLOBAL_H
#define EXTENSIONSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#include <QLoggingCategory>

#if defined(EXTENSIONSYSTEM_LIBRARY)
#  define MIPS_EXTENSIONSYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define MIPS_EXTENSIONSYSTEM_EXPORT Q_DECL_IMPORT
#endif

Q_DECLARE_LOGGING_CATEGORY(pluginLog)

#endif // EXTENSIONSYSTEM_GLOBAL_H
